### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by queicherius** [queicherius/runelite-time-tracking-reminder#1]
- [x] Golden master
- [x] Add config option for bird houses infobox
- [x] Add reminder for herb patch, tree patch and fruit tree patch
- [x] Add picture to Readme
- [x] Submit to plugin hub
